# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 万岁万万岁
subtitle: 'Take care of ourselves'
description: "成长是最美的行为艺术！Please take care of yourself！这里是小燚 & 1234 的行为艺术"
keywords:
author: 
  - '小燚'
  - '1234'
language: zh-cn
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://wanwansui.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

#hexo-renderer-marked
# marked:
#   gfm: true
#   breaks: true
#   pedantic: false
#   smartLists: true
#   smartypants: true
  

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repository: git@github.com:wanwansui/wanwansui.github.io.git
  branch: master

#搜索
search:
  path: search.xml
  field: post

#  订阅支持：
feed:
  enable: true 
  type: rss2
  path: feed.xml
  limit: false
  hub:
  content: true
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  autodiscovery: true


#中文链接转拼音
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'


# hexo-generator-feed:
# feed: 
#   enable: true
#   type: atom
#   path: atom.xml
#   limit: 0
#   content: true
#   template: 
#     channel: 
#       title: "万岁万万岁"
#       link: https://wanwansui.github.io/
#       description: "Take care of yourself. 成长是最美的行为艺术。"
#       language: zh-cn
#       pubDate: <%= date.toGMTString() %>
#       lastBuildDate: <%= date.toGMTString() %>
#       generator: "小燚"
#     item: 
#       title: <%= post.title %>
#       link: <%= config.url + post.path %>
#       guid: <%= config.url + post.path %>
#       pubDate: <%= date.toGMTString() %>
#       description: <%= post.excerpt %>

